-   id: check-version-bumped
    name: check-version-bumped
    description: Check if version has been bumped.
    entry: check-version-bumped
    language: python
    types: [python]
    require_serial: true

-   id: only-module-imports
    name: only-module-imports
    description: Check if only modules imported.
    entry: only-module-imports
    language: python
    types: [python]

-   id: copyright-check
    name: copyright-check
    description: Check if copyrights are updated.
    entry: copyright-checker
    language: python
